server:
  port: 7801


spring:
  application:
    name: registry


eureka:
  instance:
    namespace: registry
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.namespace}:${server.port}/eureka/


security:
  user:
    name: user
    password: 123123

