server:
  port: 7800

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lixiaopeng98/peng-cloud
          search-paths: config-warehouse
          username: 1048834827@qq.com
          password: tkdshyxw5
  rabbitmq:
    host: rabbitmq
  zipkin:
    base-url: http://cloud-zipkin:7821/
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      percentage: 1

eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7801/eureka/
management:
  security:
    enabled: false


