server:
  port: 7800

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lixiaopeng98/peng-cloud
          search-paths: config-warehouse
  rabbitmq:
    host: rabbitmq

eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7801/eureka/



