server:
  port: 7810
  context-path: /uaa

management:
  context-path: /mgmt
  security:
    enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:user
    driver-class-name: org.h2.Driver
    data-username: user
    data-password: 123123
  jpa:
    show-sql: true
  application:
    name: cloud-auth-server



  redis:
    cluster:
      nodes: 47.94.208.130:7001,47.94.208.130:7002,47.94.208.130:7003,47.94.208.130:7004,47.94.208.130:7005
      # 执行命令超时时间
      command-timeout: 15000
      # 重试次数
      max-attempts: 5
      # 跨集群执行命令时要遵循的最大重定向数量
      max-redirects: 3
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 16
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      test-on-borrow: true



eureka:
  instance:
    health-check-url: ${server.context-path}${management.context-path}/health
    status-page-url-path: ${server.context-path}${management.context-path}/info
    metadata-map:
      management.context-path: ${server.context-path}${management.context-path}
    hostname: registry
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:123123@registry:7801/eureka/

authserver:
    hostname: cloud-auth-server
    port: 7810
    contextPath: /uaa

security:
  user:
    name: user
    password: 123123
  oauth2:
    resource:
      user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/current