server:
  port: 7802
spring:
  application:
    name: spring-feign-one
  cloud:
    config:
      uri: http://registry:7801/eureka/
      fail-fast: true
      username: user
      password: 123123
      retry:
          initial-interval: 2000
          max-interval: 10000
          multiplier: 2
          max-attempts: 10
