spring:
  application:
    name: cloud-feign-one
  cloud:
    config:
      name: cloud-feign-one.yml
      uri: http://config:7800/
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 10
