server:
  port: 7811

spring:
  application:
    name: cloud-feign-two
eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7801/eureka/
    healthcheck:
      enabled: false
ribbon:
  eureka:
    enabled: true

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100
