server:
  port: 7803

spring:
  application:
    name: cloud-feign-two
eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
#    metadata-map:
#      user.name: user
#      user.password: 123123
  client:
    service-url:
#      defaultZone: http://${security.user.name}:${security.user.password}@registry:7801/eureka/
      defaultZone: http://${eureka.instance.hostname}:7801/eureka/
ribbon:
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
#security:
#  user:
#    name: user
#    password: 123123
#      defaultZone: http://registry:7801/eureka/
#
#authserver:
#  hostname: cloud-auth-service
#  port: 7810
#  contextPath: /uaa
#
#security:
#  user:
#    name: user
#    password: 123123
#  oauth2:
#    resource:
#      user-info-uri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/current
#    client:
#      clientId: spring-feign-two
#      clientSecret: ${security.user.password}
#      accessTokenUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/token
#      grant-type: client_credentials
#      scope: server
#  basic:
#    enabled: false

#spring:
#  application:
#    name: spring-feign-one
#  cloud:
#    config:
#      uri: http://config:8888:7801/eureka/
#      fail-fast: true
#      username: user
#      password: 123123
#      retry:
#          initial-interval: 2000
#          max-interval: 10000
#          multiplier: 2
#          max-attempts: 10